workdir: ./storage
mode: node

node:
  name: AggregationNode
  healthcheck: 3600.0
  allow_resource_download: true

  token_projects_initial:
    - name: california_clients
      token: 58981bcbab77ef4b8e01207134c38873e0936a9ab88cd76b243a2e2c85390b94
    - name: california_nodes
      token: e0936a9ab88cd76b243a2e2c85390b9458981bcbab77ef4b8e01207134c38873

  protocol: http
  interface: 0.0.0.0
  url: "http://server:1456"  # Updated to match the server container name in the Docker network
  port: 1456

join:
  first: True

database:
  username: ${DATABASE_USER?Missing DATABASE_USER for server}
  password: ${DATABASE_PASS?Missing DATABASE_PASS for server}
  scheme: ${DATABASE_SCHEMA?Missing DATABASE_SCHEMA for server}
  dialect: postgresql   # Changed to postgres to match your docker-compose service
  host: flotta_database   # Updated to match the database container name in Docker Compose
  port: 5432
  memory: False

datasources:
  - name: CIFAR-10
    type: csv
    path: "/flotta/data/server_public_test.csv"  # Updated to match the mounted path in Docker Compose
    kind: file
    token: 58981bcbab77ef4b8e01207134c38873e0936a9ab88cd76b243a2e2c85390b94
